proxy:
  title: ShinyProxy
  #  logo-url: https://link/to/your/logo.png
  landing-page: /
  favicon-path: favicon.ico
  heartbeat-rate: 10000
  heartbeat-timeout: 600000
  container-wait-time: 90000
  port: 3838
  # authentication: simple
  # admin-groups: admins
  # # Example: 'simple' authentication configuration
  # users:
  #   - name: admin
  #     password: password
  #     groups: admins
  #   - name: user
  #     password: password
  #     groups: users
  # Docker configuration
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
    - id: rshiny-flask-app
      display-name: test Shiny App
      description: R shiny with Python Flask backend
      container-cmd: ["sh", "run.sh"]
      container-image: rshiny-flask-app
      access-groups: [admins, users]
      # container-env:
      #   SCRIPT_NAME: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH').replaceFirst('/$','')}"
      #target-path: "#{proxy.getRuntimeValue('SHINYPROXY_PUBLIC_PATH')}"

logging:
  file:
    name: shinyproxy.log

spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
